version: "3.8"
services:
  db:
    image: postgres
    container_name: library-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
  #    volumes:
  #      - local_pgdata:/var/lib/postgresql/data
  #      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
